<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.5</Version>
    <Description>BetterDiscordRichPresence</Description>
    <PackageProjectUrl>https://github.com/RayaSerahill/BetterDiscordRichpresence</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <RootNamespace>BetterDiscordRichPresence</RootNamespace>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ECommons" Version="3.2.0.17" />
    </ItemGroup>

    <ItemGroup>
        <None Include="Resources/binaries/WineRPCBridge.exe">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="Resources/binaries/WineRPCBridgeLICENSE.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
